//! upload-pack: request parsing, object closure walk, pack writing, and the
//! streamed response body (milestone 2).
//!
//! Streaming design: every callback deterministically regenerates the full
//! response body and slices out its chunk. Objects are immutable and never
//! deleted, and the wants/haves are pinned in the callback token, so the
//! regenerated bytes are identical on every call - no cross-callback state,
//! and a push landing mid-clone cannot corrupt the stream. The cost is a full
//! body rebuild per chunk; fine within the 5B-instruction query budget for
//! packs up to tens of MiB, and optimizable later with a prefix-hash cache.

use crate::object;
use crate::smart_http::{parse_pkt_lines, pkt_line, FLUSH_PKT};
use crate::store::{self, ObjectType, Oid};
use ic_dev_kit_rs::http::{StreamingCallbackHttpResponse, StreamingCallbackToken};
use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};
use std::collections::{BTreeSet, VecDeque};

/// HTTP-body bytes per streaming response; margin under the 3 MiB query cap.
pub const STREAM_CHUNK: usize = 1_500_000;

/// Sideband band-1 data bytes per pkt (side-band-64k: 65520-byte pkts).
const SIDEBAND_DATA: usize = 65515;

pub struct UploadPackRequest {
    pub wants: Vec<Oid>,
    pub haves: Vec<Oid>,
    pub done: bool,
    pub sideband: bool,
}

pub fn parse_request(body: &[u8]) -> Result<UploadPackRequest, String> {
    let mut req = UploadPackRequest {
        wants: Vec::new(),
        haves: Vec::new(),
        done: false,
        sideband: false,
    };
    let mut pos = 0;
    while pos < body.len() {
        let (lines, consumed) = parse_pkt_lines(&body[pos..])?;
        if consumed == 0 {
            break;
        }
        pos += consumed;
        for line in &lines {
            let line = std::str::from_utf8(line)
                .map_err(|_| "non-utf8 pkt line")?
                .trim_end();
            if line.is_empty() {
                continue; // flush marker
            }
            if let Some(rest) = line.strip_prefix("want ") {
                let hex = rest.get(..40).ok_or("short want line")?;
                req.wants.push(store::parse_oid(hex)?);
                // Capabilities the client selected ride on the first want line.
                if rest[40..].contains("side-band-64k") {
                    req.sideband = true;
                }
            } else if let Some(rest) = line.strip_prefix("have ") {
                req.haves
                    .push(store::parse_oid(rest.get(..40).ok_or("short have line")?)?);
            } else if line == "done" {
                req.done = true;
            } else {
                // shallow/deepen/filter would land here; none are advertised.
                return Err(format!("unsupported request line: {line}"));
            }
        }
    }
    if req.wants.is_empty() {
        return Err("no wants in request".into());
    }
    Ok(req)
}

// --- closure walk -----------------------------------------------------------

/// Child object ids referenced by a non-blob object.
fn children(object_type: ObjectType, content: &[u8]) -> Result<Vec<Oid>, String> {
    Ok(match object_type {
        ObjectType::Blob => Vec::new(),
        ObjectType::Commit => {
            let refs = object::commit_refs(content)?;
            let mut out = vec![refs.tree];
            out.extend(refs.parents);
            out
        }
        ObjectType::Tag => vec![object::tag_target(content)?],
        ObjectType::Tree => object::tree_entries(content)?
            .into_iter()
            .map(|e| e.oid)
            .collect(),
    })
}

/// BFS over the object graph from `roots`, skipping anything in `stop`.
/// Blobs are never inflated - their type comes from the value prefix and they
/// have no children. `strict` errors on missing objects (wants must be fully
/// present); the lenient form skips them (haves may reference history we
/// never had).
fn reachable(
    roots: &[Oid],
    stop: &BTreeSet<Oid>,
    strict: bool,
) -> Result<Vec<(Oid, ObjectType)>, String> {
    let mut visited: BTreeSet<Oid> = BTreeSet::new();
    let mut out = Vec::new();
    let mut queue: VecDeque<Oid> = roots.iter().copied().collect();
    while let Some(oid) = queue.pop_front() {
        if visited.contains(&oid) || stop.contains(&oid) {
            continue;
        }
        let Some(stored) = store::get_object_stored(&oid) else {
            if strict {
                return Err(format!("missing object {}", store::oid_hex(&oid)));
            }
            continue;
        };
        visited.insert(oid);
        out.push((oid, stored.object_type));
        if stored.object_type != ObjectType::Blob {
            for child in children(stored.object_type, &stored.content())? {
                if !visited.contains(&child) {
                    queue.push_back(child);
                }
            }
        }
    }
    Ok(out)
}

/// Objects to pack: everything reachable from `wants` minus everything
/// reachable from the haves we actually possess (the client has those; the
/// lenient walk skips haves we never had).
pub fn closure(wants: &[Oid], haves: &[Oid]) -> Result<Vec<(Oid, ObjectType)>, String> {
    let have_set: BTreeSet<Oid> = reachable(haves, &BTreeSet::new(), false)?
        .into_iter()
        .map(|(oid, _)| oid)
        .collect();
    reachable(wants, &have_set, true)
}

// --- pack format ------------------------------------------------------------
// Encoder (upload-pack) and decoder (receive-pack) of the same wire layout,
// kept adjacent so they cannot drift apart.

const OFS_DELTA: u8 = 6;
const REF_DELTA: u8 = 7;

/// Pack entry header: type in bits 6-4 of the first byte, size in little-
/// endian 4+7+7+... bit groups with MSB continuation.
fn push_entry_header(pack: &mut Vec<u8>, object_type: ObjectType, size: u64) {
    let mut byte = ((object_type as u8) << 4) | (size & 0x0F) as u8;
    let mut size = size >> 4;
    while size > 0 {
        pack.push(byte | 0x80);
        byte = (size & 0x7F) as u8;
        size >>= 7;
    }
    pack.push(byte);
}

/// Decode an entry header at `pos`: (type code, inflated size, next pos).
/// For delta entries the size is the inflated size of the delta data.
fn parse_entry_header(data: &[u8], mut pos: usize) -> Result<(u8, u64, usize), String> {
    let mut byte = *data.get(pos).ok_or("truncated pack entry")?;
    pos += 1;
    let type_code = (byte >> 4) & 0x07;
    let mut size = (byte & 0x0F) as u64;
    let mut shift = 4;
    while byte & 0x80 != 0 {
        byte = *data.get(pos).ok_or("truncated size varint")?;
        pos += 1;
        size |= ((byte & 0x7F) as u64) << shift;
        shift += 7;
    }
    Ok((type_code, size, pos))
}

/// OFS_DELTA base offset: big-endian 7-bit groups where each continuation
/// adds an implicit +1 (git's "offset encoding").
fn parse_ofs_offset(data: &[u8], mut pos: usize) -> Result<(u64, usize), String> {
    let mut byte = *data.get(pos).ok_or("truncated ofs offset")?;
    pos += 1;
    let mut offset = (byte & 0x7F) as u64;
    while byte & 0x80 != 0 {
        byte = *data.get(pos).ok_or("truncated ofs offset")?;
        pos += 1;
        offset = ((offset + 1) << 7) | (byte & 0x7F) as u64;
    }
    Ok((offset, pos))
}

/// Little-endian 7-bit size varint used inside delta data.
fn parse_delta_size(delta: &[u8], mut pos: usize) -> Result<(u64, usize), String> {
    let mut size = 0u64;
    let mut shift = 0;
    loop {
        let byte = *delta.get(pos).ok_or("truncated delta size")?;
        pos += 1;
        size |= ((byte & 0x7F) as u64) << shift;
        shift += 7;
        if byte & 0x80 == 0 {
            return Ok((size, pos));
        }
    }
}

/// Apply a git delta (copy/insert instruction stream) to `base`.
pub fn apply_delta(base: &[u8], delta: &[u8]) -> Result<Vec<u8>, String> {
    let (src_size, pos) = parse_delta_size(delta, 0)?;
    if src_size as usize != base.len() {
        return Err("delta source size mismatch".into());
    }
    let (dst_size, mut pos) = parse_delta_size(delta, pos)?;
    let mut out = Vec::with_capacity(dst_size as usize);
    while pos < delta.len() {
        let op = delta[pos];
        pos += 1;
        if op & 0x80 != 0 {
            // Copy from base: bits 0-3 select offset bytes, 4-6 size bytes.
            let mut offset = 0u64;
            let mut size = 0u64;
            for i in 0..4 {
                if op & (1 << i) != 0 {
                    offset |= (*delta.get(pos).ok_or("truncated copy offset")? as u64) << (8 * i);
                    pos += 1;
                }
            }
            for i in 0..3 {
                if op & (1 << (4 + i)) != 0 {
                    size |= (*delta.get(pos).ok_or("truncated copy size")? as u64) << (8 * i);
                    pos += 1;
                }
            }
            if size == 0 {
                size = 0x10000;
            }
            let start = offset as usize;
            let end = start.checked_add(size as usize).ok_or("copy overflow")?;
            out.extend_from_slice(base.get(start..end).ok_or("delta copy out of range")?);
        } else if op != 0 {
            // Insert literal bytes.
            let n = op as usize;
            out.extend_from_slice(delta.get(pos..pos + n).ok_or("delta insert out of range")?);
            pos += n;
        } else {
            return Err("delta opcode 0".into());
        }
    }
    if out.len() as u64 != dst_size {
        return Err("delta target size mismatch".into());
    }
    Ok(out)
}

/// Inflate one zlib stream starting at `pos`; returns (content, bytes consumed).
fn inflate_from(data: &[u8], pos: usize) -> Result<(Vec<u8>, usize), String> {
    let mut decoder = flate2::read::ZlibDecoder::new(&data[pos..]);
    let mut out = Vec::new();
    std::io::Read::read_to_end(&mut decoder, &mut out).map_err(|e| format!("pack zlib: {e}"))?;
    Ok((out, decoder.total_in() as usize))
}

/// Parse a received pack, resolve deltas (in-pack via OFS/REF, thin-pack
/// bases via the store), verify the trailer, and store every object.
/// Returns the stored oids in pack order.
pub fn ingest_pack(data: &[u8]) -> Result<Vec<Oid>, String> {
    if data.len() < 32 || &data[..4] != b"PACK" {
        return Err("bad pack header".into());
    }
    let version = u32::from_be_bytes(data[4..8].try_into().unwrap());
    if version != 2 && version != 3 {
        return Err(format!("unsupported pack version {version}"));
    }
    let count = u32::from_be_bytes(data[8..12].try_into().unwrap());
    let content_end = data.len() - 20;
    let digest: [u8; 20] = Sha1::digest(&data[..content_end]).into();
    if digest.as_slice() != &data[content_end..] {
        return Err("pack checksum mismatch".into());
    }

    let mut pos = 12;
    // Entry start offset -> oid, for OFS_DELTA bases; resolved contents for
    // both delta kinds (a <=2 MiB ingress pack inflates comfortably in heap).
    let mut by_offset: std::collections::BTreeMap<usize, Oid> = std::collections::BTreeMap::new();
    let mut resolved: std::collections::BTreeMap<Oid, (ObjectType, Vec<u8>)> =
        std::collections::BTreeMap::new();
    let mut oids = Vec::with_capacity(count as usize);

    for _ in 0..count {
        let entry_start = pos;
        let (type_code, size, p) = parse_entry_header(data, pos)?;
        pos = p;
        let (object_type, content) = match type_code {
            1..=4 => {
                let (content, consumed) = inflate_from(data, pos)?;
                pos += consumed;
                if content.len() as u64 != size {
                    return Err("entry size mismatch".into());
                }
                (ObjectType::from_pack_code(type_code).unwrap(), content)
            }
            OFS_DELTA => {
                let (offset, p) = parse_ofs_offset(data, pos)?;
                pos = p;
                let base_start = entry_start
                    .checked_sub(offset as usize)
                    .ok_or("ofs delta offset out of range")?;
                let base_oid = by_offset
                    .get(&base_start)
                    .ok_or("ofs delta base not found")?;
                let (delta, consumed) = inflate_from(data, pos)?;
                pos += consumed;
                if delta.len() as u64 != size {
                    return Err("delta size mismatch".into());
                }
                let (base_type, base) = resolved.get(base_oid).ok_or("ofs base unresolved")?;
                (*base_type, apply_delta(base, &delta)?)
            }
            REF_DELTA => {
                let base_oid = Oid::try_from(
                    data.get(pos..pos + 20).ok_or("truncated ref delta base")?,
                )
                .unwrap();
                pos += 20;
                let (delta, consumed) = inflate_from(data, pos)?;
                pos += consumed;
                if delta.len() as u64 != size {
                    return Err("delta size mismatch".into());
                }
                // Thin packs reference bases only the server has.
                let (base_type, base) = match resolved.get(&base_oid) {
                    Some((t, c)) => (*t, c.clone()),
                    None => store::get_object_parsed(&base_oid).ok_or_else(|| {
                        format!("ref delta base {} missing", store::oid_hex(&base_oid))
                    })?,
                };
                (base_type, apply_delta(&base, &delta)?)
            }
            t => return Err(format!("unsupported pack entry type {t}")),
        };
        let oid = store::put_object(object_type, &content);
        by_offset.insert(entry_start, oid);
        resolved.insert(oid, (object_type, content));
        oids.push(oid);
    }
    if pos != content_end {
        return Err("pack length mismatch".into());
    }
    Ok(oids)
}

/// A version-2 packfile with no deltas: stored zlib streams are emitted
/// verbatim after their entry headers.
pub fn build_pack(objects: &[(Oid, ObjectType)]) -> Vec<u8> {
    let mut pack = Vec::new();
    pack.extend_from_slice(b"PACK");
    pack.extend_from_slice(&2u32.to_be_bytes());
    pack.extend_from_slice(&(objects.len() as u32).to_be_bytes());
    for (oid, _) in objects {
        let stored = store::get_object_stored(oid).expect("closure object exists");
        push_entry_header(&mut pack, stored.object_type, stored.size as u64);
        pack.extend_from_slice(stored.zlib());
    }
    let digest: [u8; 20] = Sha1::digest(&pack).into();
    pack.extend_from_slice(&digest);
    pack
}

// --- response body & streaming ----------------------------------------------

pub enum UploadPackReply {
    /// Negotiation continues; the client has not sent `done` yet. With no
    /// multi_ack advertised, policy is to single-NAK every round.
    Negotiating(Vec<u8>),
    /// The full response body: NAK then the (possibly sideband-framed) pack.
    Pack(Vec<u8>),
}

pub fn respond(req: &UploadPackRequest) -> Result<UploadPackReply, String> {
    if !req.done {
        return Ok(UploadPackReply::Negotiating(pkt_line(b"NAK\n")));
    }
    Ok(UploadPackReply::Pack(response_body(req)?))
}

fn response_body(req: &UploadPackRequest) -> Result<Vec<u8>, String> {
    let objects = closure(&req.wants, &req.haves)?;
    let pack = build_pack(&objects);
    let mut body = pkt_line(b"NAK\n");
    if req.sideband {
        // Per frame: 4 hex length bytes + 1 band byte, written in place.
        body.reserve(pack.len() + (pack.len() / SIDEBAND_DATA + 1) * 5 + FLUSH_PKT.len());
        for chunk in pack.chunks(SIDEBAND_DATA) {
            body.extend_from_slice(format!("{:04x}", chunk.len() + 5).as_bytes());
            body.push(1); // band 1: pack data
            body.extend_from_slice(chunk);
        }
        body.extend_from_slice(FLUSH_PKT);
    } else {
        body.extend_from_slice(&pack);
    }
    Ok(body)
}

/// The immutable request state a callback needs to regenerate the body,
/// JSON-packed into the token's `key`; the chunk number rides in the token's
/// own `index` field.
#[derive(Serialize, Deserialize)]
struct TokenState {
    w: Vec<String>,
    h: Vec<String>,
    sb: bool,
}

pub fn stream_token(req: &UploadPackRequest, next_chunk: u64) -> StreamingCallbackToken {
    let state = TokenState {
        w: req.wants.iter().map(store::oid_hex).collect(),
        h: req.haves.iter().map(store::oid_hex).collect(),
        sb: req.sideband,
    };
    StreamingCallbackToken {
        key: serde_json::to_string(&state).expect("token serializes"),
        content_encoding: "identity".to_string(),
        index: candid::Nat::from(next_chunk),
        sha256: None,
    }
}

pub fn next_chunk(token: &StreamingCallbackToken) -> Result<StreamingCallbackHttpResponse, String> {
    let index = u64::try_from(&token.index.0).map_err(|_| "bad token index")? as usize;
    let state: TokenState =
        serde_json::from_str(&token.key).map_err(|e| format!("bad token: {e}"))?;
    let req = UploadPackRequest {
        wants: state
            .w
            .iter()
            .map(|h| store::parse_oid(h))
            .collect::<Result<_, _>>()?,
        haves: state
            .h
            .iter()
            .map(|h| store::parse_oid(h))
            .collect::<Result<_, _>>()?,
        done: true,
        sideband: state.sb,
    };
    let body = response_body(&req)?;
    let start = index * STREAM_CHUNK;
    if start >= body.len() {
        return Err("token past end of body".into());
    }
    let end = (start + STREAM_CHUNK).min(body.len());
    Ok(StreamingCallbackHttpResponse {
        body: body[start..end].to_vec(),
        token: (end < body.len()).then(|| StreamingCallbackToken {
            index: candid::Nat::from(index as u64 + 1),
            ..token.clone()
        }),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_header_varint() {
        let mut small = Vec::new();
        push_entry_header(&mut small, ObjectType::Blob, 5);
        assert_eq!(small, vec![0b0011_0101]); // type 3, size 5, no continuation

        let mut large = Vec::new();
        push_entry_header(&mut large, ObjectType::Commit, 0b1010_0111_1100); // 2684
        // low 4 bits (0b1100) + type 1 + MSB; then 7 bits 0b010_0111 + MSB
        // (the remaining group 0b1010_0111 exceeds 7 bits); then final 0b1.
        assert_eq!(large, vec![0b1001_1100, 0b1010_0111, 0b0000_0001]);
    }

    #[test]
    fn delta_copy_and_insert() {
        let base = b"hello world";
        // src size 11, dst size 16; copy(offset 0, size 5) + insert " there" +
        // copy(offset 5, size 6) -> "hello there world"... sizes: 5+6+6 = 17.
        let mut delta = vec![11, 17];
        delta.push(0b1001_0001); // copy: offset byte 0 present, size byte 0 present
        delta.extend_from_slice(&[0, 5]);
        delta.push(6); // insert 6 literal bytes
        delta.extend_from_slice(b" there");
        delta.push(0b1001_0001);
        delta.extend_from_slice(&[5, 6]);
        assert_eq!(apply_delta(base, &delta).unwrap(), b"hello there world");

        assert!(apply_delta(b"wrong len", &delta).is_err());
    }

    #[test]
    fn ingest_round_trips_built_pack() {
        // Build objects, pack them with our writer, wipe nothing (the store
        // is content-addressed so re-ingest is idempotent), ingest, compare.
        let blob = store::put_object(ObjectType::Blob, b"round trip");
        let mut tree = Vec::new();
        tree.extend_from_slice(b"100644 f\0");
        tree.extend_from_slice(blob.as_slice());
        let tree = store::put_object(ObjectType::Tree, &tree);
        let pack = build_pack(&[(blob, ObjectType::Blob), (tree, ObjectType::Tree)]);

        let oids = ingest_pack(&pack).unwrap();
        assert_eq!(oids, vec![blob, tree]);

        // Corrupt the trailer: must be rejected.
        let mut bad = pack.clone();
        let n = bad.len();
        bad[n - 1] ^= 0xFF;
        assert!(ingest_pack(&bad).unwrap_err().contains("checksum"));
    }

    #[test]
    fn ingest_resolves_ref_delta_against_store() {
        let base_content = b"the quick brown fox jumps over the lazy dog";
        let base = store::put_object(ObjectType::Blob, base_content);

        // Delta: copy the whole base, then append "!".
        let mut delta = vec![base_content.len() as u8, base_content.len() as u8 + 1];
        delta.push(0b1001_0001);
        delta.extend_from_slice(&[0, base_content.len() as u8]);
        delta.push(1);
        delta.push(b'!');

        // Hand-build a one-entry thin pack: REF_DELTA against the stored base.
        let mut pack = Vec::new();
        pack.extend_from_slice(b"PACK");
        pack.extend_from_slice(&2u32.to_be_bytes());
        pack.extend_from_slice(&1u32.to_be_bytes());
        // Entry header for REF_DELTA (type 7), size = delta.len().
        let size = delta.len() as u64;
        let mut byte = (REF_DELTA << 4) | (size & 0x0F) as u8;
        let mut rest = size >> 4;
        while rest > 0 {
            pack.push(byte | 0x80);
            byte = (rest & 0x7F) as u8;
            rest >>= 7;
        }
        pack.push(byte);
        pack.extend_from_slice(base.as_slice());
        let mut enc = flate2::write::ZlibEncoder::new(Vec::new(), flate2::Compression::default());
        std::io::Write::write_all(&mut enc, &delta).unwrap();
        pack.extend_from_slice(&enc.finish().unwrap());
        let digest: [u8; 20] = Sha1::digest(&pack).into();
        pack.extend_from_slice(&digest);

        let oids = ingest_pack(&pack).unwrap();
        assert_eq!(oids.len(), 1);
        let (t, content) = store::get_object_parsed(&oids[0]).unwrap();
        assert_eq!(t, ObjectType::Blob); // delta inherits the base's type
        assert_eq!(content, b"the quick brown fox jumps over the lazy dog!");
    }

    #[test]
    fn closure_walks_commit_tree_blob() {
        let blob = store::put_object(ObjectType::Blob, b"hello");
        let mut tree = Vec::new();
        tree.extend_from_slice(b"100644 hello.txt\0");
        tree.extend_from_slice(blob.as_slice());
        let tree = store::put_object(ObjectType::Tree, &tree);
        let commit = store::put_object(
            ObjectType::Commit,
            format!(
                "tree {}\nauthor a <a@a> 0 +0000\ncommitter a <a@a> 0 +0000\n\nmsg\n",
                store::oid_hex(&tree)
            )
            .as_bytes(),
        );

        let objects = closure(&[commit], &[]).unwrap();
        assert_eq!(objects.len(), 3);

        // Everything the client already has drops out.
        let objects = closure(&[commit], &[commit]).unwrap();
        assert!(objects.is_empty());

        let pack = build_pack(&closure(&[commit], &[]).unwrap());
        assert_eq!(&pack[..4], b"PACK");
        assert_eq!(u32::from_be_bytes(pack[8..12].try_into().unwrap()), 3);
        let digest: [u8; 20] = Sha1::digest(&pack[..pack.len() - 20]).into();
        assert_eq!(&pack[pack.len() - 20..], digest.as_slice());
    }
}
