//! upload-pack: request parsing, object closure walk, pack writing, and the
//! streamed response body (milestone 2).
//!
//! Streaming design: every callback deterministically regenerates the full
//! response body and slices out its chunk. Objects are immutable and never
//! deleted, and the wants/haves are pinned in the callback token, so the
//! regenerated bytes are identical on every call - no cross-callback state,
//! and a push landing mid-clone cannot corrupt the stream. The cost is a full
//! body rebuild per chunk; fine within the 5B-instruction query budget for
//! packs up to tens of MiB, and optimizable later with a prefix-hash cache.

use crate::object;
use crate::smart_http::{parse_pkt_lines, pkt_line, FLUSH_PKT};
use crate::store::{self, ObjectType, Oid};
use ic_dev_kit_rs::http::{StreamingCallbackHttpResponse, StreamingCallbackToken};
use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};
use std::collections::{BTreeSet, VecDeque};

/// HTTP-body bytes per streaming response; margin under the 3 MiB query cap.
pub const STREAM_CHUNK: usize = 1_500_000;

/// Sideband band-1 data bytes per pkt (side-band-64k: 65520-byte pkts).
const SIDEBAND_DATA: usize = 65515;

pub struct UploadPackRequest {
    pub wants: Vec<Oid>,
    pub haves: Vec<Oid>,
    pub done: bool,
    pub sideband: bool,
}

pub fn parse_request(body: &[u8]) -> Result<UploadPackRequest, String> {
    let mut req = UploadPackRequest {
        wants: Vec::new(),
        haves: Vec::new(),
        done: false,
        sideband: false,
    };
    let mut pos = 0;
    while pos < body.len() {
        let (lines, consumed) = parse_pkt_lines(&body[pos..])?;
        if consumed == 0 {
            break;
        }
        pos += consumed;
        for line in &lines {
            let line = std::str::from_utf8(line)
                .map_err(|_| "non-utf8 pkt line")?
                .trim_end();
            if line.is_empty() {
                continue; // flush marker
            }
            if let Some(rest) = line.strip_prefix("want ") {
                let hex = rest.get(..40).ok_or("short want line")?;
                req.wants.push(store::parse_oid(hex)?);
                // Capabilities the client selected ride on the first want line.
                if rest[40..].contains("side-band-64k") {
                    req.sideband = true;
                }
            } else if let Some(rest) = line.strip_prefix("have ") {
                req.haves
                    .push(store::parse_oid(rest.get(..40).ok_or("short have line")?)?);
            } else if line == "done" {
                req.done = true;
            } else {
                // shallow/deepen/filter would land here; none are advertised.
                return Err(format!("unsupported request line: {line}"));
            }
        }
    }
    if req.wants.is_empty() {
        return Err("no wants in request".into());
    }
    Ok(req)
}

// --- closure walk -----------------------------------------------------------

/// Child object ids referenced by a non-blob object.
fn children(object_type: ObjectType, content: &[u8]) -> Result<Vec<Oid>, String> {
    Ok(match object_type {
        ObjectType::Blob => Vec::new(),
        ObjectType::Commit => {
            let refs = object::commit_refs(content)?;
            let mut out = vec![refs.tree];
            out.extend(refs.parents);
            out
        }
        ObjectType::Tag => vec![object::tag_target(content)?],
        ObjectType::Tree => object::tree_entries(content)?
            .into_iter()
            .map(|e| e.oid)
            .collect(),
    })
}

/// BFS over the object graph from `roots`, skipping anything in `stop`.
/// Blobs are never inflated - their type comes from the value prefix and they
/// have no children. `strict` errors on missing objects (wants must be fully
/// present); the lenient form skips them (haves may reference history we
/// never had).
fn reachable(
    roots: &[Oid],
    stop: &BTreeSet<Oid>,
    strict: bool,
) -> Result<Vec<(Oid, ObjectType)>, String> {
    let mut visited: BTreeSet<Oid> = BTreeSet::new();
    let mut out = Vec::new();
    let mut queue: VecDeque<Oid> = roots.iter().copied().collect();
    while let Some(oid) = queue.pop_front() {
        if visited.contains(&oid) || stop.contains(&oid) {
            continue;
        }
        let Some(stored) = store::get_object_stored(&oid) else {
            if strict {
                return Err(format!("missing object {}", store::oid_hex(&oid)));
            }
            continue;
        };
        visited.insert(oid);
        out.push((oid, stored.object_type));
        if stored.object_type != ObjectType::Blob {
            for child in children(stored.object_type, &stored.content())? {
                if !visited.contains(&child) {
                    queue.push_back(child);
                }
            }
        }
    }
    Ok(out)
}

/// Objects to pack: everything reachable from `wants` minus everything
/// reachable from the haves we actually possess (the client has those; the
/// lenient walk skips haves we never had).
pub fn closure(wants: &[Oid], haves: &[Oid]) -> Result<Vec<(Oid, ObjectType)>, String> {
    let have_set: BTreeSet<Oid> = reachable(haves, &BTreeSet::new(), false)?
        .into_iter()
        .map(|(oid, _)| oid)
        .collect();
    reachable(wants, &have_set, true)
}

// --- pack format ------------------------------------------------------------
// (Milestone 3's pack indexer parses this same layout in reverse; keep its
// decoder adjacent to these when it lands.)

/// Pack entry header: type in bits 6-4 of the first byte, size in little-
/// endian 4+7+7+... bit groups with MSB continuation.
fn push_entry_header(pack: &mut Vec<u8>, object_type: ObjectType, size: u64) {
    let mut byte = ((object_type as u8) << 4) | (size & 0x0F) as u8;
    let mut size = size >> 4;
    while size > 0 {
        pack.push(byte | 0x80);
        byte = (size & 0x7F) as u8;
        size >>= 7;
    }
    pack.push(byte);
}

/// A version-2 packfile with no deltas: stored zlib streams are emitted
/// verbatim after their entry headers.
pub fn build_pack(objects: &[(Oid, ObjectType)]) -> Vec<u8> {
    let mut pack = Vec::new();
    pack.extend_from_slice(b"PACK");
    pack.extend_from_slice(&2u32.to_be_bytes());
    pack.extend_from_slice(&(objects.len() as u32).to_be_bytes());
    for (oid, _) in objects {
        let stored = store::get_object_stored(oid).expect("closure object exists");
        push_entry_header(&mut pack, stored.object_type, stored.size as u64);
        pack.extend_from_slice(stored.zlib());
    }
    let digest: [u8; 20] = Sha1::digest(&pack).into();
    pack.extend_from_slice(&digest);
    pack
}

// --- response body & streaming ----------------------------------------------

pub enum UploadPackReply {
    /// Negotiation continues; the client has not sent `done` yet. With no
    /// multi_ack advertised, policy is to single-NAK every round.
    Negotiating(Vec<u8>),
    /// The full response body: NAK then the (possibly sideband-framed) pack.
    Pack(Vec<u8>),
}

pub fn respond(req: &UploadPackRequest) -> Result<UploadPackReply, String> {
    if !req.done {
        return Ok(UploadPackReply::Negotiating(pkt_line(b"NAK\n")));
    }
    Ok(UploadPackReply::Pack(response_body(req)?))
}

fn response_body(req: &UploadPackRequest) -> Result<Vec<u8>, String> {
    let objects = closure(&req.wants, &req.haves)?;
    let pack = build_pack(&objects);
    let mut body = pkt_line(b"NAK\n");
    if req.sideband {
        // Per frame: 4 hex length bytes + 1 band byte, written in place.
        body.reserve(pack.len() + (pack.len() / SIDEBAND_DATA + 1) * 5 + FLUSH_PKT.len());
        for chunk in pack.chunks(SIDEBAND_DATA) {
            body.extend_from_slice(format!("{:04x}", chunk.len() + 5).as_bytes());
            body.push(1); // band 1: pack data
            body.extend_from_slice(chunk);
        }
        body.extend_from_slice(FLUSH_PKT);
    } else {
        body.extend_from_slice(&pack);
    }
    Ok(body)
}

/// The immutable request state a callback needs to regenerate the body,
/// JSON-packed into the token's `key`; the chunk number rides in the token's
/// own `index` field.
#[derive(Serialize, Deserialize)]
struct TokenState {
    w: Vec<String>,
    h: Vec<String>,
    sb: bool,
}

pub fn stream_token(req: &UploadPackRequest, next_chunk: u64) -> StreamingCallbackToken {
    let state = TokenState {
        w: req.wants.iter().map(store::oid_hex).collect(),
        h: req.haves.iter().map(store::oid_hex).collect(),
        sb: req.sideband,
    };
    StreamingCallbackToken {
        key: serde_json::to_string(&state).expect("token serializes"),
        content_encoding: "identity".to_string(),
        index: candid::Nat::from(next_chunk),
        sha256: None,
    }
}

pub fn next_chunk(token: &StreamingCallbackToken) -> Result<StreamingCallbackHttpResponse, String> {
    let index = u64::try_from(&token.index.0).map_err(|_| "bad token index")? as usize;
    let state: TokenState =
        serde_json::from_str(&token.key).map_err(|e| format!("bad token: {e}"))?;
    let req = UploadPackRequest {
        wants: state
            .w
            .iter()
            .map(|h| store::parse_oid(h))
            .collect::<Result<_, _>>()?,
        haves: state
            .h
            .iter()
            .map(|h| store::parse_oid(h))
            .collect::<Result<_, _>>()?,
        done: true,
        sideband: state.sb,
    };
    let body = response_body(&req)?;
    let start = index * STREAM_CHUNK;
    if start >= body.len() {
        return Err("token past end of body".into());
    }
    let end = (start + STREAM_CHUNK).min(body.len());
    Ok(StreamingCallbackHttpResponse {
        body: body[start..end].to_vec(),
        token: (end < body.len()).then(|| StreamingCallbackToken {
            index: candid::Nat::from(index as u64 + 1),
            ..token.clone()
        }),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_header_varint() {
        let mut small = Vec::new();
        push_entry_header(&mut small, ObjectType::Blob, 5);
        assert_eq!(small, vec![0b0011_0101]); // type 3, size 5, no continuation

        let mut large = Vec::new();
        push_entry_header(&mut large, ObjectType::Commit, 0b1010_0111_1100); // 2684
        // low 4 bits (0b1100) + type 1 + MSB; then 7 bits 0b010_0111 + MSB
        // (the remaining group 0b1010_0111 exceeds 7 bits); then final 0b1.
        assert_eq!(large, vec![0b1001_1100, 0b1010_0111, 0b0000_0001]);
    }

    #[test]
    fn closure_walks_commit_tree_blob() {
        let blob = store::put_object(ObjectType::Blob, b"hello");
        let mut tree = Vec::new();
        tree.extend_from_slice(b"100644 hello.txt\0");
        tree.extend_from_slice(blob.as_slice());
        let tree = store::put_object(ObjectType::Tree, &tree);
        let commit = store::put_object(
            ObjectType::Commit,
            format!(
                "tree {}\nauthor a <a@a> 0 +0000\ncommitter a <a@a> 0 +0000\n\nmsg\n",
                store::oid_hex(&tree)
            )
            .as_bytes(),
        );

        let objects = closure(&[commit], &[]).unwrap();
        assert_eq!(objects.len(), 3);

        // Everything the client already has drops out.
        let objects = closure(&[commit], &[commit]).unwrap();
        assert!(objects.is_empty());

        let pack = build_pack(&closure(&[commit], &[]).unwrap());
        assert_eq!(&pack[..4], b"PACK");
        assert_eq!(u32::from_be_bytes(pack[8..12].try_into().unwrap()), 3);
        let digest: [u8; 20] = Sha1::digest(&pack[..pack.len() - 20]).into();
        assert_eq!(&pack[pack.len() - 20..], digest.as_slice());
    }
}
