//! upload-pack: request parsing, object closure walk, pack writing, and the
//! streamed response body (milestone 2).
//!
//! Streaming design: every callback deterministically regenerates the full
//! response body and slices out its chunk. Objects are immutable and never
//! deleted, and the wants/haves are pinned in the callback token, so the
//! regenerated bytes are identical on every call - no cross-callback state,
//! and a push landing mid-clone cannot corrupt the stream. The cost is a full
//! body rebuild per chunk; fine within the 5B-instruction query budget for
//! packs up to tens of MiB, and optimizable later with a prefix-hash cache.

use crate::smart_http::{parse_pkt_lines, pkt_line, FLUSH_PKT};
use crate::store::{self, ObjectType, Oid};
use ic_dev_kit_rs::http::{StreamingCallbackHttpResponse, StreamingCallbackToken};
use serde::{Deserialize, Serialize};
use sha1::{Digest, Sha1};
use std::collections::{BTreeSet, VecDeque};

/// HTTP-body bytes per streaming response; margin under the 3 MiB query cap.
pub const STREAM_CHUNK: usize = 1_500_000;

/// Sideband band-1 data bytes per pkt (side-band-64k: 65520-byte pkts).
const SIDEBAND_DATA: usize = 65515;

pub struct UploadPackRequest {
    pub wants: Vec<Oid>,
    pub haves: Vec<Oid>,
    pub done: bool,
    pub sideband: bool,
}

pub fn parse_request(body: &[u8]) -> Result<UploadPackRequest, String> {
    let mut req = UploadPackRequest {
        wants: Vec::new(),
        haves: Vec::new(),
        done: false,
        sideband: false,
    };
    let mut pos = 0;
    while pos < body.len() {
        let (lines, consumed) = parse_pkt_lines(&body[pos..])?;
        if consumed == 0 {
            break;
        }
        pos += consumed;
        for line in &lines {
            let line = std::str::from_utf8(line)
                .map_err(|_| "non-utf8 pkt line")?
                .trim_end();
            if line.is_empty() {
                continue; // flush marker
            }
            if let Some(rest) = line.strip_prefix("want ") {
                let hex = rest.get(..40).ok_or("short want line")?;
                req.wants.push(parse_hex_oid(hex)?);
                // Capabilities the client selected ride on the first want line.
                if rest[40..].contains("side-band-64k") {
                    req.sideband = true;
                }
            } else if let Some(rest) = line.strip_prefix("have ") {
                req.haves
                    .push(parse_hex_oid(rest.get(..40).ok_or("short have line")?)?);
            } else if line == "done" {
                req.done = true;
            } else {
                // shallow/deepen/filter would land here; none are advertised.
                return Err(format!("unsupported request line: {line}"));
            }
        }
    }
    if req.wants.is_empty() {
        return Err("no wants in request".into());
    }
    Ok(req)
}

fn parse_hex_oid(hex: &str) -> Result<Oid, String> {
    let bytes = hex::decode(hex).map_err(|e| format!("bad oid: {e}"))?;
    Oid::try_from(bytes.as_slice()).map_err(|_| "oid must be 20 bytes".to_string())
}

// --- closure walk -----------------------------------------------------------

/// Child object ids referenced by an object.
fn children(object_type: ObjectType, content: &[u8]) -> Result<Vec<Oid>, String> {
    match object_type {
        ObjectType::Blob => Ok(Vec::new()),
        ObjectType::Commit | ObjectType::Tag => {
            // Headers are ASCII lines up to the first empty line:
            // commit: "tree <hex>", "parent <hex>"*; tag: "object <hex>".
            let header_end = content
                .windows(2)
                .position(|w| w == b"\n\n")
                .unwrap_or(content.len());
            let mut out = Vec::new();
            for line in content[..header_end].split(|&b| b == b'\n') {
                let line = std::str::from_utf8(line).map_err(|_| "non-utf8 object header")?;
                for prefix in ["tree ", "parent ", "object "] {
                    if let Some(hex) = line.strip_prefix(prefix) {
                        out.push(parse_hex_oid(hex.get(..40).ok_or("short header oid")?)?);
                    }
                }
            }
            Ok(out)
        }
        ObjectType::Tree => {
            // Entries: "<mode> <name>\0" + 20-byte sha, repeated.
            let mut out = Vec::new();
            let mut i = 0;
            while i < content.len() {
                let nul = content[i..]
                    .iter()
                    .position(|&b| b == 0)
                    .ok_or("malformed tree entry")?
                    + i;
                let sha = content.get(nul + 1..nul + 21).ok_or("malformed tree sha")?;
                out.push(Oid::try_from(sha).unwrap());
                i = nul + 21;
            }
            Ok(out)
        }
    }
}

/// BFS over the object graph from `roots`, skipping anything in `stop`.
/// `strict` errors on missing objects (wants must be fully present); the
/// lenient form skips them (haves may reference history we never had).
fn reachable(
    roots: &[Oid],
    stop: &BTreeSet<Oid>,
    strict: bool,
) -> Result<Vec<(Oid, ObjectType)>, String> {
    let mut visited: BTreeSet<Oid> = BTreeSet::new();
    let mut out = Vec::new();
    let mut queue: VecDeque<Oid> = roots.iter().copied().collect();
    while let Some(oid) = queue.pop_front() {
        if visited.contains(&oid) || stop.contains(&oid) {
            continue;
        }
        let Some((object_type, content)) = store::get_object_parsed(&oid) else {
            if strict {
                return Err(format!("missing object {}", hex::encode(oid.as_slice())));
            }
            continue;
        };
        visited.insert(oid);
        out.push((oid, object_type));
        for child in children(object_type, &content)? {
            if !visited.contains(&child) {
                queue.push_back(child);
            }
        }
    }
    Ok(out)
}

/// Objects to pack: everything reachable from `wants` minus everything
/// reachable from the `haves` we actually possess (the client has those).
pub fn closure(wants: &[Oid], haves: &[Oid]) -> Result<Vec<(Oid, ObjectType)>, String> {
    let known_haves: Vec<Oid> = haves
        .iter()
        .copied()
        .filter(store::has_object)
        .collect();
    let have_set: BTreeSet<Oid> = reachable(&known_haves, &BTreeSet::new(), false)?
        .into_iter()
        .map(|(oid, _)| oid)
        .collect();
    reachable(wants, &have_set, true)
}

// --- pack writer ------------------------------------------------------------

/// Pack entry header: type in bits 6-4 of the first byte, size in little-
/// endian 4+7+7+... bit groups with MSB continuation.
fn push_entry_header(pack: &mut Vec<u8>, object_type: ObjectType, size: u64) {
    let mut byte = ((object_type as u8) << 4) | (size & 0x0F) as u8;
    let mut size = size >> 4;
    while size > 0 {
        pack.push(byte | 0x80);
        byte = (size & 0x7F) as u8;
        size >>= 7;
    }
    pack.push(byte);
}

/// A version-2 packfile with no deltas: stored zlib streams are emitted
/// verbatim after their entry headers.
pub fn build_pack(objects: &[(Oid, ObjectType)]) -> Vec<u8> {
    let mut pack = Vec::new();
    pack.extend_from_slice(b"PACK");
    pack.extend_from_slice(&2u32.to_be_bytes());
    pack.extend_from_slice(&(objects.len() as u32).to_be_bytes());
    for (oid, _) in objects {
        let (object_type, size, zlib) =
            store::get_object_deflated(oid).expect("closure object exists");
        push_entry_header(&mut pack, object_type, size as u64);
        pack.extend_from_slice(&zlib);
    }
    let digest: [u8; 20] = Sha1::digest(&pack).into();
    pack.extend_from_slice(&digest);
    pack
}

// --- response body & streaming ----------------------------------------------

/// Full HTTP body for a `done` upload-pack request: NAK, then the pack
/// (sideband-framed when the client asked for side-band-64k).
pub fn response_body(req: &UploadPackRequest) -> Result<Vec<u8>, String> {
    let objects = closure(&req.wants, &req.haves)?;
    let pack = build_pack(&objects);
    let mut body = pkt_line(b"NAK\n");
    if req.sideband {
        body.reserve(pack.len() + pack.len() / SIDEBAND_DATA * 24 + 32);
        for chunk in pack.chunks(SIDEBAND_DATA) {
            let mut payload = Vec::with_capacity(chunk.len() + 1);
            payload.push(1u8); // band 1: pack data
            payload.extend_from_slice(chunk);
            body.extend_from_slice(&pkt_line(&payload));
        }
        body.extend_from_slice(FLUSH_PKT);
    } else {
        body.extend_from_slice(&pack);
    }
    Ok(body)
}

/// Everything a callback needs to regenerate the body, JSON-packed into the
/// token's `key` (the gateway round-trips the token verbatim; the fixed
/// asset-canister token shape has no better slot, so `index` stays 0).
#[derive(Serialize, Deserialize)]
struct TokenState {
    w: Vec<String>,
    h: Vec<String>,
    sb: bool,
    i: usize,
}

pub fn stream_token(req: &UploadPackRequest, next_chunk: usize) -> StreamingCallbackToken {
    let state = TokenState {
        w: req.wants.iter().map(|o| hex::encode(o.as_slice())).collect(),
        h: req.haves.iter().map(|o| hex::encode(o.as_slice())).collect(),
        sb: req.sideband,
        i: next_chunk,
    };
    StreamingCallbackToken {
        key: serde_json::to_string(&state).expect("token serializes"),
        content_encoding: "identity".to_string(),
        index: candid::Nat::from(0u8),
        sha256: None,
    }
}

pub fn next_chunk(token: &StreamingCallbackToken) -> Result<StreamingCallbackHttpResponse, String> {
    let state: TokenState =
        serde_json::from_str(&token.key).map_err(|e| format!("bad token: {e}"))?;
    let req = UploadPackRequest {
        wants: state.w.iter().map(|h| parse_hex_oid(h)).collect::<Result<_, _>>()?,
        haves: state.h.iter().map(|h| parse_hex_oid(h)).collect::<Result<_, _>>()?,
        done: true,
        sideband: state.sb,
    };
    let body = response_body(&req)?;
    let start = state.i * STREAM_CHUNK;
    if start >= body.len() {
        return Err("token past end of body".into());
    }
    let end = (start + STREAM_CHUNK).min(body.len());
    Ok(StreamingCallbackHttpResponse {
        body: body[start..end].to_vec(),
        token: (end < body.len()).then(|| stream_token(&req, state.i + 1)),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entry_header_varint() {
        let mut small = Vec::new();
        push_entry_header(&mut small, ObjectType::Blob, 5);
        assert_eq!(small, vec![0b0011_0101]); // type 3, size 5, no continuation

        let mut large = Vec::new();
        push_entry_header(&mut large, ObjectType::Commit, 0b1010_0111_1100); // 2684
        // low 4 bits (0b1100) + type 1 + MSB; then 7 bits 0b010_0111 + MSB
        // (the remaining group 0b1010_0111 exceeds 7 bits); then final 0b1.
        assert_eq!(large, vec![0b1001_1100, 0b1010_0111, 0b0000_0001]);
    }

    #[test]
    fn closure_walks_commit_tree_blob() {
        let blob = store::put_object(ObjectType::Blob, b"hello");
        let mut tree = Vec::new();
        tree.extend_from_slice(b"100644 hello.txt\0");
        tree.extend_from_slice(blob.as_slice());
        let tree = store::put_object(ObjectType::Tree, &tree);
        let commit = store::put_object(
            ObjectType::Commit,
            format!(
                "tree {}\nauthor a <a@a> 0 +0000\ncommitter a <a@a> 0 +0000\n\nmsg\n",
                hex::encode(tree.as_slice())
            )
            .as_bytes(),
        );

        let objects = closure(&[commit], &[]).unwrap();
        assert_eq!(objects.len(), 3);

        // Everything the client already has drops out.
        let objects = closure(&[commit], &[commit]).unwrap();
        assert!(objects.is_empty());

        let pack = build_pack(&closure(&[commit], &[]).unwrap());
        assert_eq!(&pack[..4], b"PACK");
        assert_eq!(u32::from_be_bytes(pack[8..12].try_into().unwrap()), 3);
        let digest: [u8; 20] = Sha1::digest(&pack[..pack.len() - 20]).into();
        assert_eq!(&pack[pack.len() - 20..], digest.as_slice());
    }
}
