#!/usr/bin/env node
// Regenerates core/bls12-381.js: the BLS12-381 short-signature verifier the
// certified reader (core/verifier.js, readCanisterState) uses to check an IC
// state certificate's subnet signature. Verifying one is the only piece of
// the core that cannot be written small and checked by eye, so it is an
// audited implementation vendored whole -- @noble/curves, bundled into a
// classic-script IIFE so the loader can inline it and an extension's
// background worker can importScripts it.
//
// The bundle is a function of the pinned versions below and nothing else:
// run this script and `git diff core/bls12-381.js` must be empty. A reviewer
// who does not want to trust the committed file regenerates it the same way.
// It is bundled unminified so the file can be read against the package.
//
//   node tools/vendor-bls.mjs          # rewrite core/bls12-381.js
//   node tools/vendor-bls.mjs --check  # exit 1 if it differs from a fresh bundle
//
// Needs node and npm with network access to the registry, once.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

// Bumping either: read the package's changelog, regenerate, run
// tools/certified-test.mjs (the mainnet vectors and the tamper suite).
const CURVES = '2.4.0';
const HASHES = '2.4.0';
const ESBUILD = '0.28.2';

// Non-ASCII the pinned package's comments contain, and its ASCII spelling.
const ASCII = {
  '\u22c5': '*', '\u2212': '-', '\u2014': '--', '\u2013': '-', '\u00a7': 'section ',
  '\u00b2': '^2', '\u00b3': '^3', '\u207f': '^n', '\u2099': '_n',
  '\u03b1': 'alpha', '\u03b2': 'beta', '\u03a6': 'Phi', '\u2208': 'in', '\u220b': 'contains',
};

const out = new URL('../core/bls12-381.js', import.meta.url);
const work = mkdtempSync(join(tmpdir(), 'ic-git-bls.'));
try {
  writeFileSync(join(work, 'package.json'), JSON.stringify({ name: 'vendor', private: true }));
  execFileSync('npm', ['install', '--no-audit', '--no-fund', '--ignore-scripts', '--silent',
    `@noble/curves@${CURVES}`, `@noble/hashes@${HASHES}`, `esbuild@${ESBUILD}`], { cwd: work, stdio: 'inherit' });
  // Only the short-signature mode (signatures in G1, public keys in G2),
  // which is the IC's. Nothing else of the package is reachable.
  writeFileSync(join(work, 'entry.js'),
    "import { bls12_381 } from '@noble/curves/bls12-381.js';\n" +
    'export const shortSignatures = bls12_381.shortSignatures;\n');
  execFileSync(join(work, 'node_modules', '.bin', 'esbuild'), ['entry.js', '--bundle', '--format=iife',
    '--global-name=NobleBls', '--target=es2022', '--legal-comments=inline', '--outfile=bundle.js'], { cwd: work, stdio: 'inherit' });
  let bundle = readFileSync(join(work, 'bundle.js'), 'utf8');
  // The loader inlines this in a <script>: these two sequences would end
  // the element or put the parser in the escaped state.
  for (const bad of ['\x3c!--', '\x3c/script']) {
    if (bundle.includes(bad)) throw new Error(`bundle contains "${bad}"; it cannot be inlined`);
  }
  // The repo is ASCII-only (.githooks/pre-commit). The package's comments
  // use a few mathematical and typographic characters; each is spelled out
  // here, the same way every time, so the result still reads against the
  // package. Anything not in this table fails the build rather than being
  // guessed at -- in code, a character this does not expect could matter.
  for (const [from, to] of Object.entries(ASCII)) bundle = bundle.split(from).join(to);
  const left = bundle.match(/[^\x00-\x7f]/g);
  if (left) throw new Error('bundle has non-ASCII this script does not know: ' + [...new Set(left)].map(c => 'U+' + c.codePointAt(0).toString(16).padStart(4, '0')).join(' '));
  const sha = createHash('sha256').update(bundle).digest('hex');
  const text = '// === bls ===\n'
    + '// GENERATED by tools/vendor-bls.mjs; do not edit. @noble/curves ' + CURVES
    + ' (bls12_381.shortSignatures only), @noble/hashes ' + HASHES + ', esbuild ' + ESBUILD + '.\n'
    + '// sha256 of the bundle below: ' + sha + '\n'
    + '// Used by core/verifier.js readCanisterState to verify IC state certificates.\n'
    + bundle.replace(/\n$/, '') + '\n// === end bls ===\n';
  const now = (() => { try { return readFileSync(out, 'utf8'); } catch { return ''; } })();
  if (process.argv.includes('--check')) {
    if (now !== text) { console.error('core/bls12-381.js differs from a fresh bundle of the pinned versions'); process.exit(1); }
    console.log('core/bls12-381.js is a fresh bundle of the pinned versions (sha256 ' + sha + ')');
  } else {
    writeFileSync(out, text);
    console.log((now === text ? 'unchanged' : 'wrote') + ' core/bls12-381.js (' + text.length + ' bytes, bundle sha256 ' + sha + ')');
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
